polls/urls.py
from django.conf.urls import patterns, url

from polls import views

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'),
)

pybursa/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from pybursa.views import *
from quadratic.views import *
from feedbacks.views import *

urlpatterns = patterns('',
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', index, name="index"),
    url(r'^contact/$', contact, name="contact"),
    url(r'^students/', include('students.urls', namespace="students")),
    url(r'^courses/', include('courses.urls', namespace="courses")),
    url(r'^quadratic/', include('quadratic.urls', namespace="quadratic")),
    url(r'^coaches/', include('coaches.urls', namespace="coaches")),
    url(r'^feedback/$', FeedbackView.as_view(), name="feedback"),
)

students/urls.py
from django.conf.urls import patterns, include, url
from students import views

urlpatterns = patterns('',
    url(r'^$', views.StudentListView.as_view(), name='list_view'),
    url(r'^(?P<pk>\d+)/$', views.StudentDetailView.as_view(), name='detail'),
    url(r'^add/$', views.StudentCreateView.as_view(), name='add'),
    url(r'^edit/(?P<pk>\d+)/$', views.StudentUpdateView.as_view(), name='edit'),
    url(r'^remove/(?P<pk>\d+)/$', views.StudentDeleteView.as_view(), name='remove'),
)

students/models.py
# -*- coding: utf-8 -*-
from django.db import models
from courses.models import Course

class Student(models.Model):
    name = models.CharField(max_length=255)
    surname = models.CharField(max_length=255)
    date_of_birth = models.DateField()
    email = models.EmailField()
    phone = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    skype = models.CharField(max_length=255)
    courses = models.ManyToManyField(Course)
    
    

students/forms.py
from django import forms


from students.models import Student

class StudentModelForm(forms.ModelForm):

    class Meta:
        model = Student
        fields = '__all__'
    

students/views.py
from django.shortcuts import render, redirect
from students.models import Student
from students.forms import StudentModelForm
from django.contrib import messages
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

import logging
logger = logging.getLogger(__name__)


class StudentDetailView(DetailView):
    model = Student    
    def get_context_data(self, **kwargs):
		context = super(StudentDetailView, self).get_context_data(**kwargs)
		logger.debug("Students detail view has been debugged")
		logger.info("Logger of students detail view informs you!")
		logger.warning("Logger of students detail view warns you!")
		logger.error("Students detail view went wrong!")
		return context

class StudentListView(ListView):
    model = Student
    paginate_by = 2
    
    def get_queryset(self):
        if 'course_id' in self.request.GET:
            student_list = Student.objects.filter(courses=self.request.GET['course_id'])
            #paginator = Paginator(student_list, 2)
            #page = self.request.GET.get('page')
            #try:
              #  contacts = paginator.page(page)
           # except PageNotAnInteger:
        # If page is not an integer, deliver first page.
               # contacts = paginator.page(1)
            #except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
                #contacts = paginator.page(paginator.num_pages)
        else:
            student_list = Student.objects.all()
            #paginator = Paginator(student_list, 2)
            #page = self.request.GET.get('page')
            #try:
            #    contacts = paginator.page(page)
            #except PageNotAnInteger:
        # If page is not an integer, deliver first page.
               # contacts = paginator.page(1)
           # except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
               # contacts = paginator.page(paginator.num_pages)
        return student_list
    
class StudentCreateView(CreateView):
    model = Student
    success_url = reverse_lazy('students:list_view')
    def get_context_data(self, **kwargs):
        context = super(StudentCreateView, self).get_context_data(**kwargs)
        context['title'] = 'Student registration'
        return context
    def form_valid(self, form):
        form.save()
        messages.success(self.request, 'Student %s %s has been successfully added.' % (
                form.instance.name, form.instance.surname))
        return super(StudentCreateView, self).form_valid(form)        
                
class StudentUpdateView(UpdateView):
    model = Student
    def get_success_url(self, **kwargs):
		return reverse_lazy('students:edit', args=(self.object.pk,))
    def get_context_data(self, **kwargs):
        context = super(StudentUpdateView, self).get_context_data(**kwargs)
        context['title'] = 'Student info update'
        return context
    def form_valid(self, form):
        
        messages.success(self.request, 'Info on the student has been successfully changed.')
        return super(StudentUpdateView, self).form_valid(form)
                  
class StudentDeleteView(DeleteView):
    model = Student
    success_url = reverse_lazy('students:list_view')
    def get_context_data(self, **kwargs):
        context = super(StudentDeleteView, self).get_context_data(**kwargs)
        context['title'] = 'Student info suppression'
        return context
    def delete(self, request, *args, **kwargs):
        stud = super(StudentDeleteView, self).delete(request, *args, **kwargs)
        messages.success(self.request, 'Info on %s %s has been sucessfully deleted.' % (
                self.object.name, self.object.surname))
        return stud
        

        

templates/students/add.html
{% extends 'base.html' %}

{% load staticfiles %}


{% block title %}Students add page{% endblock title %}


{% block nav_class_students %}active{% endblock nav_class_students %}


{% block content %}
    <div class="col-lg-12">

        <h2>Создание нового студента</h2>

        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            {# <button type="submit" class="btn btn-default">Создать</button> #}
            <input type="submit" value="Create"/>
        </form>
    </div>
{% endblock content %}

templates/students/detail.html
{% extends 'base.html' %}

{% load staticfiles %}


{% block title %}Students Detail{% endblock title %}


{% block nav_class_students %}active{% endblock nav_class_students %}


{% block content %}
    <div class="col-lg-12">
        <div class="well student_detail">
            <h2>{{ student.surname }} {{ student.name }}</h2>
            <img src="{% static 'images/avatar_empty.png' %}" alt="img">
            <table class="table table-striped table-hover">
                <tbody>
                <tr>
                    <td>Дата рождения</td>
                    <td>{{ student.date_of_birth|date:'j F, Y' }}</td>
                </tr>
                <tr>
                    <td>адрес</td>
                    <td>{{ student.address }}</td>
                </tr>
                <tr>
                    <td>почта</td>
                    <td>{{ student.email }}</td>
                </tr>
                <tr>
                    <td>логин skype</td>
                    <td>{{ student.skype }}</td>
                </tr>
                <tr>
                    <td>телефон</td>
                    <td>{{ student.phone }}</td>
                </tr>
                <td>Courses</td>
                <td>{% for course in student.courses.all %}
                    <a href="{% url 'courses:detail' course.id %}">{{ course }}</a>
                    <br>{% endfor %}</td>
                </tbody>
            </table>
            <h3>Perfomance</h3>
            <table class="table table-hover perfomance">
                <thead>
                <th>Course</th>
                <th>Week</th>
                <th>Control Type</th>
                <th>Grade</th>
                </thead>
                <tbody>
                <tr>
                    <td>PyBursa</td>
                    <td>Week1</td>
                    <td>Tests</td>
                    <td>99%</td>
                </tr>
                <tr>
                    <td></td>
                    <td></td>
                    <td>Problem Tasks №1</td>
                    <td>98%</td>
                </tr>
                <tr>
                    <td></td>
                    <td></td>
                    <td>Problem Tasks №2</td>
                    <td>100%</td>
                </tr>
                <tr>
                    <td></td>
                    <td>Week2</td>
                    <td>Tests</td>
                    <td>100%</td>
                </tr>
                <tr>
                    <td></td>
                    <td></td>
                    <td>Problem Tasks №1</td>
                    <td>99%</td>
                </tr>
                <tr>
                    <td></td>
                    <td></td>
                    <td>Problem Tasks №2</td>
                    <td>95%</td>
                </tr>
                </tbody>
            </table>
    </div>
</div>
{% endblock content %}

templates/students/edit.html
{% extends "base.html" %}

{% block title %}{{ student.name }} {{ student.surname }} Edit Form{% endblock %}

{% block selected_students %}selected{% endblock %}

{% block content %}
        <div class="container at_center">
	<br>
	{% if messages %}
	    {% for message in messages %}
	    <div class="alert alert-{% if message.tags %}{{ message.tags }}{% else %}info{% endif %} alert-dismissible" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		{{ message }}
	    </div>
	    {% endfor %}
	{% endif %}
	<h1 class="glow_cyan_t">Edit Jedi data</h1>
		<form method="post">
			{% csrf_token %}
			<table>
			{{ form.as_table}}
			</table>
			<input type="submit" value="Save" />
		</form>
    	</div>
{% endblock content %}

{% block footer %}"footer atbottom"{% endblock %}

templates/students/list.html
{% extends 'base.html' %}


{% load staticfiles %}


{% block title %}Students List{% endblock title %}


{% block nav_class_students %}active{% endblock nav_class_students %}


{% block content %}
    <div class="col-lg-12">
        <h2>Список курса PyBursa</h2>
        <a href="{% url 'students:add' %}" class="btn btn-success">Add Students</a>

        {% if messages %}
            <div class="alert alert-info alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                {% for message in messages %} {{ message }} {% endfor %}
            </div>
        {% endif %}
        <table class="table table-striped table-hover list_student">
            <thead>
            <tr>
                <th>#</th>
                <th>фамилия имя</th>
                <th>адрес</th>
                <th>Skype</th>
                <th colspan="3">курсы</th>
            </tr>
            </thead>
            <tbody>
            {% for list_student in list_students %}
                <tr>
                    <td>{{ list_student.id }}</td>
                    <td>
                        <a href="{% url 'students:detail' list_student.id %}">{{ list_student.surname }} {{ list_student.name }}</a>
                    </td>
                    <td>{{ list_student.address }}</td>
                    <td>{{ list_student.skype }}</td>
                    <td>{% for course in list_student.courses.all %}
                        <a href="{% url 'courses:detail' course.id %}">{{ course.name|upper }}</a>
                        <br>{% endfor %}</td>
                    <td><a href="{% url 'students:edit' list_student.id %}" class="btn btn-info">Изменить</a></td>
                    <td><a href="{% url 'students:remove' list_student.id %}" class="btn btn-info">Удалить</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
</div>
{% endblock content %}

templates/students/list_view.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
   
    <title>PyStudents</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    
    <link rel="shortcut icon" href="{% static 'images/python.ico' %}" type="image/x-icon">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    
  </head>
  <body>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><a href="{% url 'index' %}">Главная</a></li>
          <li><a href="{% url 'contact' %}">Контакты</a></li>
          <li><a href="{% url 'students:list_view' %}">Студенты</a></li>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  <div class="jumbotron">
    <div class="container">
      <h1>Список студентов</h1>

    </div>
  </div>
  
  
  <table class="table table-hover">
    <thead>
      <tr>
        <th>#</th>
        <th>Фамилия и имя</th>
        <th>Адрес</th>
        <th>Skype</th>
        <th>курсы</th>
        
      </tr>
    </thead>
    <tbody>
    {% for student in students %}
      <tr>
        <td>{{ student.id }}</td>
        <td><a href="{% url 'students:detail' student.id %}">{{ student.name }} {{ student.surname }}</a></td>
        <td>{{ student.address }}</td>
        <td>{{ student.skype }}</td>
        <td>
            {% for course in student.courses.all %}
                <p><a href="{% url 'courses:detail' course.id %}">{{ course }}</a></p>
            {% endfor %} 
        </td>
        
      </tr>
    {% endfor %}
    </tbody>
  </table>
  
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>

templates/students/remove.html
{% extends 'base.html' %}

{% load staticfiles %}


{% block title %}Students add page{% endblock title %}


{% block nav_class_students %}active{% endblock nav_class_students %}


{% block content %}
    <div class="col-lg-12">

        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-
                        {% if message.tags %}{{ message.tags }}{% else %}info{% endif %} alert-dismissible"
                     role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}

        <h2>Студент {{ student.name }} {{ student.surname }} будет удален</h2>

        <form method="post">
            {% csrf_token %}
            <input type="submit" value="Remove"/>
        </form>


    </div>
{% endblock content %}

templates/students/student_confirm_delete.html
{% extends "base.html" %}


{% load staticfiles %}


{% block title %}{{ title }}{% endblock title %}


{% block blow_students %}active{% endblock blow_students %}


{% block content %}
         
    <h3> Студент {{ student.name }} {{ student.surname }} будет удален</h3>
      <form method="post">
        {% csrf_token %}
        
        <input type="submit" value="Удалить" />
     </form>
  </div>
  
  
{% endblock content %}  
    

templates/students/student_detail.html
{% extends "base.html" %}


{% load staticfiles %}


{% block title %}PyStudent{% endblock title %}


{% block content %}

  <table class="table table-condensed">
    <thead><h3>{{ student.name }} {{ student.surname }}</h3>
      <tr>
        <th>Информация о студенте</th>
      </tr>
    </thead>
    <tbody>
      
      <tr>
        <td>дата рождения</td>
        <td>{{ student.date_of_birth }}</td>
      </tr>
      <tr>
        <td>адрес</td>
        <td>{{ student.address }}</td>
      </tr>
      <tr>
        <td>почта</td>
        <td>{{ student.email }}</td>
      </tr>
      <tr>
        <td>логин skype</td>
        <td>{{ student.skype }}</td>
      </tr>
      <tr>
        <td>телефон</td>
        <td>{{ student.phone }}</td>
      </tr>
      <tr>
        <td>курсы</td>
        <td>
        {% for course in student.courses.all %}
            <p><a href="{% url 'courses:detail' course.id %}"> {{ course }}</a></p>
        {% endfor %}
            
        </td>
      

    </tbody>
  </table>

{% endblock content %}  

templates/students/student_form.html
{% extends "base.html" %}


{% load staticfiles %}


{% block title %}{{ title }}{% endblock title %}


{% block blow_students %}active{% endblock blow_students %}


{% block content %}
  <div class='container'>
    <h3> Создание нового студента </h3>
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Создать" />
     </form>
  </div>
  
{% endblock content %}  
    

templates/students/student_list.html
{% extends "base.html" %}


{% load staticfiles %}


{% block title %}PyStudents{% endblock title %}





{% block content %}
  {% if messages %}
        <div class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            {% for message in messages %}{{ message }}{% endfor %}
        </div>
    {% endif %}
  <div>
    <button class="btn"><a href="{% url 'students:add' %}">Добавить нового студента</a></button>
  </div>
  <div class="jumbotron">
    <div class="container">
      <h1>Список студентов</h1>

    </div>
  </div>
  
  
  <table class="table table-hover">
    <thead>
      <tr>
        <th>#</th>
        <th>Фамилия и имя</th>
        <th>Адрес</th>
        <th>Skype</th>
        <th>курсы</th>
        
      </tr>
    </thead>
    <tbody>
    {% for student in student_list %}
      <tr>
        <td>{{ student.id }}</td>
        <td><a href="{% url 'students:detail' student.id %}">{{ student.name }} {{ student.surname }}</a></td>
        <td>{{ student.address }}</td>
        <td>{{ student.skype }}</td>
        <td>
            {% for course in student.courses.all %}
                <p><a href="{% url 'courses:detail' course.id %}">{{ course }}</a></p>
            {% endfor %} 
        </td>
        <td>
            <button class="btn"><a href="{% url 'students:edit' student.id %}">Изменить</a></button>
        </td>
        <td>
            <button class="btn"><a href="{% url 'students:remove' student.id %}">Удалить</a></button>
        </td>       
      </tr>
    {% endfor %}
    </tbody>
  </table>
<nav>
  <ul class="pagination">
   
        {% if page_obj.has_previous %}
          <li><a href="?page={{ page_obj.previous_page_number }}"><< previous</a></li>
        {% endif %}
        {% for page in page_obj.paginator.page_range %}
            {% if page == page_obj.number %}
                <li class="active"><a href="?page={{ page }}">{{ page }}</a></li>
            
            {% else %}
                <li class='disabled'><a href="?page={{ page }}">{{ page }}</a></li>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}">next >></a></li>
        {% endif %}
    
  </ul>
</nav>
{% endblock content %}  
    

templates/students/student_update_form.html
{% extends "base.html" %}


{% load staticfiles %}


{% block title %}{{ title }}{% endblock title %}


{% block blow_students %}active{% endblock blow_students %}


{% block content %}
   <div class='container'>
     {% if messages %}
        <div class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            {% for message in messages %}{{ message }}{% endfor %}
        </div>
    {% endif %}}    
       
    <h3> Редактирование данных студента </h3>
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Сохранить" />
     </form>
  </div>
  
  
{% endblock content %}  
    