polls/urls.py
from django.conf.urls import patterns, url

from polls import views

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'),
)

pybursa/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from pybursa.views import *
from quadratic.views import *
from feedbacks.views import *

urlpatterns = patterns('',
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', index, name="index"),
    url(r'^contact/$', contact, name="contact"),
    url(r'^students/', include('students.urls', namespace="students")),
    url(r'^courses/', include('courses.urls', namespace="courses")),
    url(r'^quadratic/', include('quadratic.urls', namespace="quadratic")),
    url(r'^coaches/', include('coaches.urls', namespace="coaches")),
    url(r'^feedback/$', FeedbackView.as_view(), name="feedback"),
)

students/urls.py
from django.conf.urls import patterns, include, url
from students import views

urlpatterns = patterns('',
    url(r'^$', views.StudentListView.as_view(), name='list_view'),
    url(r'^(?P<pk>\d+)/$', views.StudentDetailView.as_view(), name='detail'),
    url(r'^add/$', views.StudentCreateView.as_view(), name='add'),
    url(r'^edit/(?P<pk>\d+)/$', views.StudentUpdateView.as_view(), name='edit'),
    url(r'^remove/(?P<pk>\d+)/$', views.StudentDeleteView.as_view(), name='remove'),
)

templates/include/coach_include.html
<td>
            {% for course_c in course_coach %}
            <p><a href="{% url 'courses:detail' course_c.id %}"> {{ course_c.name }}</a> студенты курса<a href="{% url 'students:list' %}?course_id={{ course_c.id }}"> <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></a></span></p>
            {% endfor %}
            
      </td>
      </tr>
      <tr>
        <td>курсы ассистент</td>
        <td>
            {% for course_a in course_assistant %}
            <p><a href="{% url 'courses:detail' course_a.id %}"> {{ course_a.name }}</a> студенты курса<a href="{% url 'students:list_view' %}?course_id={{ course_a.id }}"><span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></a></span></p>
            {% endfor %}
        </td>

templates/include/contact_include.html
{% load staticfiles %}

<div class=contact>
    <div class=c_photo> 
	<img class="img-circle glow_cyan" src="{% static photo %}"/>
    </div>
    <div class="c_contacts glow_cyan_t">
	<h1>{{ position }}</h2>
	<h3>Name: {{ name }}</h3>
	<div class=skype><h3>Skype: {{ skype }}</h3></div>
	<div class=email><h3>Email: {{ email }}</h3></div>
	<div class=phone><h3>Phone: {{ phone }}</h3></div>
    </div>
</div>	

templates/include/instructor_include.html
<table class="stud_table glow_cyan no_hover">
   <thead>
	<tr>
	   <th>{{ block_title }}</th>
	</tr>
   </thead>
   <tbody>
	<tr>
	   <td><a href="{% url 'coaches:detail' instructor.id %}">{{ instructor.user.first_name }} {{ instructor.user.last_name }}</a><br><br>{{ instructor.description }}</td>
	</tr>
   </tbody>
</table>

templates/include/messages_include.html
{% if messages %}
	<div class="alert alert-success alert-dismissible glow_cyan" role="alert">
	<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	    {% for message in messages %}
	    {{ message }}
	    {% endfor %}
	</div>
{% endif %}