courses/urls.py
from django.conf.urls import patterns, include, url
from courses import views

urlpatterns = patterns('',
    url(r'^(?P<pk>[0-9]+)/$', views.CourseDetailView.as_view(), name='detail'),
    url(r'^add/$', views.CourseCreateView.as_view(), name='add'),
    url(r'^edit/(?P<pk>[0-9]+)/$', views.CourseUpdateView.as_view(), name='edit'),
    url(r'^remove/(?P<pk>[0-9]+)/$', views.CourseDeleteView.as_view(), name='remove'),
    url(r'^(?P<pk>[0-9]+)/add_lesson$', views.add_lesson, name='add-lesson'),
)

polls/urls.py
from django.conf.urls import patterns, url

from polls import views

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'),
)

pybursa/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from pybursa.views import *
from quadratic.views import *
from feedbacks.views import *

urlpatterns = patterns('',
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', index, name="index"),
    url(r'^contact/$', contact, name="contact"),
    url(r'^students/', include('students.urls', namespace="students")),
    url(r'^courses/', include('courses.urls', namespace="courses")),
    url(r'^quadratic/', include('quadratic.urls', namespace="quadratic")),
    url(r'^coaches/', include('coaches.urls', namespace="coaches")),
    url(r'^feedback/$', FeedbackView.as_view(), name="feedback"),
)

courses/models.py
# -*- coding: utf-8 -*-
from django.db import models
from coaches.models import Coach

class Course(models.Model):
    name = models.CharField(max_length=255)
    short_description = models.CharField(max_length=255)
    description = models.TextField() 
    coach =  models.ForeignKey(Coach, blank=True, null=True, related_name='coach_courses')
    assistant =  models.ForeignKey(Coach, blank=True, null=True, related_name='assistant_courses')
    def __unicode__(self):
        return self.name
        
class Lesson(models.Model):
    subject = models.CharField(max_length=255)
    description = models.TextField() 
    course = models.ForeignKey(Course)
    order = models.PositiveIntegerField()
    def __unicode__(self):
        return self.subject

courses/forms.py
from django import forms


from courses.models import Course, Lesson

class CourseModelForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = '__all__'
        
        
class LessonModelForm(forms.ModelForm):
    class Meta:
        model = Lesson
        fields = '__all__'
    

courses/views.py
from django.shortcuts import render, redirect
from courses.models import Course, Lesson
from coaches.models import Coach
from courses.forms import *
from django.contrib import messages
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy

import logging
logger = logging.getLogger(__name__)


class CourseDetailView(DetailView):
    model = Course
    template_name = 'courses/detail.html'
    context_object_name = 'course'
    
    def get_context_data(self, **kwargs):
        context = super(CourseDetailView, self).get_context_data(**kwargs)
        context['lessons'] = Lesson.objects.filter(course=self.get_object().id)
        logger.debug('Courses detail view has been debugged')
        logger.info('Logger of courses detail view informs you!')
        logger.warning('Logger of courses detail view warns you!')
        logger.error('Courses detail view went wrong!')
        return context

class CourseCreateView(CreateView):
    model = Course
    template_name = 'courses/add.html'
    context_object_name = 'course'
    success_url = reverse_lazy('index')
    def get_context_data(self, **kwargs):
        context = super(CourseCreateView, self).get_context_data(**kwargs)
        context['title'] = 'Course creation'
        return context
    def form_valid(self, form):
        form.save()
        messages.success(self.request, 'Course %s has been successfully added.' % (
                form.instance.name))
        return super(CourseCreateView, self).form_valid(form)
    
class CourseUpdateView(UpdateView):
    model = Course
    template_name = 'courses/edit.html'
    context_object_name = 'course'
    def get_success_url(self, **kwargs):
		return reverse_lazy('courses:edit', args=(self.object.pk,))
    def get_context_data(self, **kwargs):
        context = super(CourseUpdateView, self).get_context_data(**kwargs)
        context['title'] = 'Course update'
        return context
    def form_valid(self, form):
        
        messages.success(self.request, 'The changes have been saved.')
        return super(CourseUpdateView, self).form_valid(form)
    

class CourseDeleteView(DeleteView):
    model = Course
    template_name = 'courses/remove.html'
    context_object_name = 'course'
    success_url = reverse_lazy('index')
    def get_context_data(self, **kwargs):
        context = super(CourseDeleteView, self).get_context_data(**kwargs)
        context['title'] = 'Course deletion'
        return context
    def delete(self, request, *args, **kwargs):
        cours = super(CourseDeleteView, self).delete(request, *args, **kwargs)
        messages.success(self.request, 'Course %s has been deleted.' % 
                self.object.name)
        return cours
    
    

def add_lesson(request, pk):
    res={}   
    if request.POST:
        form = LessonModelForm(request.POST)
        if form.is_valid():
            form.save()
            lesson = form.cleaned_data
            messages.success(request, 'Lesson %s has been successfully added.' % lesson['subject'])
            return redirect('courses:detail', pk)
    else:
        form = LessonModelForm(initial={ 'course': pk })
    res['form'] = form
    return render(request, 'courses/add_lesson.html', res)
        

templates/courses/add.html
{% extends "base.html" %}


{% load staticfiles %}


{% block title %}{{ title }}{% endblock title %}





{% block content %}
  <div>
    <h3> Создание нового курса </h3>
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Создать" />
     </form>
  </div>
  
{% endblock content %}  
    

templates/courses/add_lesson.html
{% extends "base.html" %}


{% load staticfiles %}


{% block title %}Lesson create{% endblock title %}





{% block content %}
  <div>
    <h3> Создание нового занятия </h3>
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Создать" />
     </form>
  </div>
  
{% endblock content %}  
    

templates/courses/detail.html
{% extends "base.html" %}


{% load staticfiles %}


{% block title %}PyBursa{% endblock title %}


{% block spec_link %}?course_id={{ course.id }}{% endblock spec_link %}


{% block content %}

{% if messages %}
 
<div class="alert alert-warning alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>{% for message in messages %}{{ message }}{% endfor %}</div>
{% endif %}
  <div>
    <button class="btn"><a href="{% url 'courses:add-lesson' course.id %}">Добавить занятие</a></button>
  </div>
    <div class="jumbotron">
      <div class="container">
        <div class="page-header">
        </div>
      </div> 
    </div> 
    <h1>{{ course }}</h1>
    <h3>{{ course.description|truncatechars:32 }}<h3> 
    <h2>План курса</h2>
    <table class="table table-hover">
      <thead>
        <tr>
          <th>#</th>
          <th>Тема</th>
          <th>Описание</th>
        </tr>
      </thead>
      <tbody>
        {% for lesson in lessons %}
          <tr>
           <td>{{ lesson.order }}</td>
           <td>{{ lesson.subject }}</td>
           <td>{{ lesson.description }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Учитель</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><a href="{% url 'coaches:detail' course.coach.id %}">{{ course.coach.first_name }} {{ course.coach.last_name }}</a></td>
          <td>{{ course.coach.description }}</td>
        </tr>
      </tbody>
    </table>
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Ассистент</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><a href="{% url 'coaches:detail' course.assistant.id %}">{{ course.assistant.first_name }} {{ course.assistant.last_name }}</a></td>
          <td>{{ course.assistant.description }}</td>
        </tr>
      </tbody>
    </table>
{% endblock content %}    
    

templates/courses/edit.html
{% extends "base.html" %}


{% load staticfiles %}


{% block title %}{{ title }}{% endblock title %}





{% block content %}
   <div>
     {% if messages %}
        <div class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            {% for message in messages %}{{ message }}{% endfor %}
        </div>
    {% endif %}    
       
    <h3> Редактирование данных курса </h3>
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Изменить" />
     </form>
  </div>
  
  
{% endblock content %}  
    

templates/courses/remove.html
{% extends "base.html" %}


{% load staticfiles %}


{% block title %}{{ title }}{% endblock title %}


{% block blow_students %}active{% endblock blow_students %}


{% block content %}
      <h3>Вы уверенны, что хотите удалить курс {{ course.name }}</h3>   
    
      <form method="post">
        {% csrf_token %}
        
        <input type="submit" value="Удалить" />
     </form>
  </div>
  
  
{% endblock content %}  
    